name: Create production promotion pull request
on:
  pull-request:
    branches:
      - staging
    types:
      - closed
      - opened
      - reopened
      - synchronize

jobs:
  productionPromotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: production
      - name: Reset promotion branch
        run: |
          git fetch origin staging:staging
          git reset --hard staging
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Merging latest staging code to master branch
          title: Staging -> Production
          body: Staging to production PR created by github-actions
          branch: staging
    checkAction:
      runs-on: ubuntu-latest
      steps:
        - name: Action
          run: echo "EventAction $github.event.action PullRequestAction $github.event.pull_request.action"
