name: Create production promotion pull request
on:
  pull_request:
    branches:
      - staging
    types:
      - closed
      - opened
      - reopened
      - synchronize

jobs:
  prepare:
    runs-on: ubuntu-latest
    name: Prepare Job Dependencies
    steps:
      - name: Get branch hash
        shell: bash
        run: echo "##[set-output name=branch_hash;]$( echo github.ref_name | md5sum | cut -c1-16 )"
    outputs:
      branch_hash: ${{ steps.get_branch_hash.outputs.branch_hash }}
  deploy:
    if: ${{ github.event.action != 'closed' }}
    runs-on: ubuntu-latest
    needs:
      - prepare
    steps:
      - name: Action
        run: echo "EventAction ${{ github.event.action }} Deploying - ${{ needs.prepare.outputs.branch_hash }}"
  actionClosed:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    needs:
      - prepare
    steps:
      - name: Action
        run: echo "EventAction ${{ github.event.action }} Closing without brackets - ${{ needs.prepare.outputs.branch_hash }}"
  actionClosedBrackets:
    if: ${{ github.event.action == 'closed' }}
    runs-on: ubuntu-latest
    needs:
      - prepare
    steps:
      - name: Action
        run: echo "EventAction ${{ github.event.action }} Closing with brackets 2 - ${{ needs.prepare.outputs.branch_hash }}"
